name: secure_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  assets: ^0.0.1
  awesome_bottom_bar: ^1.2.4
  buttons_tabbar: ^1.3.8
  floating_bottom_bar: ^0.0.2
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.1.0
  salomon_bottom_bar: ^3.3.2
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
